/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AppAccountsRouteImport } from './routes/_app/accounts'
import { Route as AppAgendaRouteImport } from './routes/_app/agenda'
import { Route as AppBudgetsRouteImport } from './routes/_app/budgets'
import { Route as AppCardsRouteImport } from './routes/_app/cards'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppGoalsRouteImport } from './routes/_app/goals'
import { Route as AppImportRouteImport } from './routes/_app/import'
import { Route as AppImportPrintsRouteImport } from './routes/_app/import-prints'
import { Route as AppIncomeRouteImport } from './routes/_app/income'
import { Route as AppInvestmentsRouteImport } from './routes/_app/investments'
import { Route as AppNotesRouteImport } from './routes/_app/notes'
import { Route as AppRechargesRouteImport } from './routes/_app/recharges'
import { Route as AppRecurringRouteImport } from './routes/_app/recurring'
import { Route as AppRoutinesRouteImport } from './routes/_app/routines'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppShoppingPlannerRouteImport } from './routes/_app/shopping-planner'
import { Route as AppStatisticsRouteImport } from './routes/_app/statistics'
import { Route as AppTasksRouteImport } from './routes/_app/tasks'
import { Route as AppTimelineRouteImport } from './routes/_app/timeline'
import { Route as AppTodayRouteImport } from './routes/_app/today'
import { Route as AppTransactionsRouteImport } from './routes/_app/transactions'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppAccountsRoute = AppAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AppRoute,
} as any)
const AppAgendaRoute = AppAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AppRoute,
} as any)
const AppBudgetsRoute = AppBudgetsRouteImport.update({
  id: '/budgets',
  path: '/budgets',
  getParentRoute: () => AppRoute,
} as any)
const AppCardsRoute = AppCardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppGoalsRoute = AppGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AppRoute,
} as any)
const AppImportRoute = AppImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AppRoute,
} as any)
const AppImportPrintsRoute = AppImportPrintsRouteImport.update({
  id: '/import-prints',
  path: '/import-prints',
  getParentRoute: () => AppRoute,
} as any)
const AppIncomeRoute = AppIncomeRouteImport.update({
  id: '/income',
  path: '/income',
  getParentRoute: () => AppRoute,
} as any)
const AppInvestmentsRoute = AppInvestmentsRouteImport.update({
  id: '/investments',
  path: '/investments',
  getParentRoute: () => AppRoute,
} as any)
const AppNotesRoute = AppNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AppRoute,
} as any)
const AppRechargesRoute = AppRechargesRouteImport.update({
  id: '/recharges',
  path: '/recharges',
  getParentRoute: () => AppRoute,
} as any)
const AppRecurringRoute = AppRecurringRouteImport.update({
  id: '/recurring',
  path: '/recurring',
  getParentRoute: () => AppRoute,
} as any)
const AppRoutinesRoute = AppRoutinesRouteImport.update({
  id: '/routines',
  path: '/routines',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppShoppingPlannerRoute = AppShoppingPlannerRouteImport.update({
  id: '/shopping-planner',
  path: '/shopping-planner',
  getParentRoute: () => AppRoute,
} as any)
const AppStatisticsRoute = AppStatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppTimelineRoute = AppTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => AppRoute,
} as any)
const AppTodayRoute = AppTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AppRoute,
} as any)
const AppTransactionsRoute = AppTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AppRoute,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/accounts': typeof AppAccountsRoute
  '/agenda': typeof AppAgendaRoute
  '/budgets': typeof AppBudgetsRoute
  '/cards': typeof AppCardsRoute
  '/dashboard': typeof AppDashboardRoute
  '/goals': typeof AppGoalsRoute
  '/import': typeof AppImportRoute
  '/import-prints': typeof AppImportPrintsRoute
  '/income': typeof AppIncomeRoute
  '/investments': typeof AppInvestmentsRoute
  '/notes': typeof AppNotesRoute
  '/recharges': typeof AppRechargesRoute
  '/recurring': typeof AppRecurringRoute
  '/routines': typeof AppRoutinesRoute
  '/settings': typeof AppSettingsRoute
  '/shopping-planner': typeof AppShoppingPlannerRoute
  '/statistics': typeof AppStatisticsRoute
  '/tasks': typeof AppTasksRoute
  '/timeline': typeof AppTimelineRoute
  '/today': typeof AppTodayRoute
  '/transactions': typeof AppTransactionsRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/accounts': typeof AppAccountsRoute
  '/agenda': typeof AppAgendaRoute
  '/budgets': typeof AppBudgetsRoute
  '/cards': typeof AppCardsRoute
  '/dashboard': typeof AppDashboardRoute
  '/goals': typeof AppGoalsRoute
  '/import': typeof AppImportRoute
  '/import-prints': typeof AppImportPrintsRoute
  '/income': typeof AppIncomeRoute
  '/investments': typeof AppInvestmentsRoute
  '/notes': typeof AppNotesRoute
  '/recharges': typeof AppRechargesRoute
  '/recurring': typeof AppRecurringRoute
  '/routines': typeof AppRoutinesRoute
  '/settings': typeof AppSettingsRoute
  '/shopping-planner': typeof AppShoppingPlannerRoute
  '/statistics': typeof AppStatisticsRoute
  '/tasks': typeof AppTasksRoute
  '/timeline': typeof AppTimelineRoute
  '/today': typeof AppTodayRoute
  '/transactions': typeof AppTransactionsRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_app/accounts': typeof AppAccountsRoute
  '/_app/agenda': typeof AppAgendaRoute
  '/_app/budgets': typeof AppBudgetsRoute
  '/_app/cards': typeof AppCardsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/goals': typeof AppGoalsRoute
  '/_app/import': typeof AppImportRoute
  '/_app/import-prints': typeof AppImportPrintsRoute
  '/_app/income': typeof AppIncomeRoute
  '/_app/investments': typeof AppInvestmentsRoute
  '/_app/notes': typeof AppNotesRoute
  '/_app/recharges': typeof AppRechargesRoute
  '/_app/recurring': typeof AppRecurringRoute
  '/_app/routines': typeof AppRoutinesRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/shopping-planner': typeof AppShoppingPlannerRoute
  '/_app/statistics': typeof AppStatisticsRoute
  '/_app/tasks': typeof AppTasksRoute
  '/_app/timeline': typeof AppTimelineRoute
  '/_app/today': typeof AppTodayRoute
  '/_app/transactions': typeof AppTransactionsRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/mcp'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/accounts'
    | '/agenda'
    | '/budgets'
    | '/cards'
    | '/dashboard'
    | '/goals'
    | '/import'
    | '/import-prints'
    | '/income'
    | '/investments'
    | '/notes'
    | '/recharges'
    | '/recurring'
    | '/routines'
    | '/settings'
    | '/shopping-planner'
    | '/statistics'
    | '/tasks'
    | '/timeline'
    | '/today'
    | '/transactions'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/mcp'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/accounts'
    | '/agenda'
    | '/budgets'
    | '/cards'
    | '/dashboard'
    | '/goals'
    | '/import'
    | '/import-prints'
    | '/income'
    | '/investments'
    | '/notes'
    | '/recharges'
    | '/recurring'
    | '/routines'
    | '/settings'
    | '/shopping-planner'
    | '/statistics'
    | '/tasks'
    | '/timeline'
    | '/today'
    | '/transactions'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/mcp'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_app/accounts'
    | '/_app/agenda'
    | '/_app/budgets'
    | '/_app/cards'
    | '/_app/dashboard'
    | '/_app/goals'
    | '/_app/import'
    | '/_app/import-prints'
    | '/_app/income'
    | '/_app/investments'
    | '/_app/notes'
    | '/_app/recharges'
    | '/_app/recurring'
    | '/_app/routines'
    | '/_app/settings'
    | '/_app/shopping-planner'
    | '/_app/statistics'
    | '/_app/tasks'
    | '/_app/timeline'
    | '/_app/today'
    | '/_app/transactions'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/accounts': {
      id: '/_app/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AppAccountsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agenda': {
      id: '/_app/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AppAgendaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/budgets': {
      id: '/_app/budgets'
      path: '/budgets'
      fullPath: '/budgets'
      preLoaderRoute: typeof AppBudgetsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cards': {
      id: '/_app/cards'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof AppCardsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/goals': {
      id: '/_app/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof AppGoalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/import': {
      id: '/_app/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AppImportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/import-prints': {
      id: '/_app/import-prints'
      path: '/import-prints'
      fullPath: '/import-prints'
      preLoaderRoute: typeof AppImportPrintsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/income': {
      id: '/_app/income'
      path: '/income'
      fullPath: '/income'
      preLoaderRoute: typeof AppIncomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/investments': {
      id: '/_app/investments'
      path: '/investments'
      fullPath: '/investments'
      preLoaderRoute: typeof AppInvestmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notes': {
      id: '/_app/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AppNotesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recharges': {
      id: '/_app/recharges'
      path: '/recharges'
      fullPath: '/recharges'
      preLoaderRoute: typeof AppRechargesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recurring': {
      id: '/_app/recurring'
      path: '/recurring'
      fullPath: '/recurring'
      preLoaderRoute: typeof AppRecurringRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/routines': {
      id: '/_app/routines'
      path: '/routines'
      fullPath: '/routines'
      preLoaderRoute: typeof AppRoutinesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/shopping-planner': {
      id: '/_app/shopping-planner'
      path: '/shopping-planner'
      fullPath: '/shopping-planner'
      preLoaderRoute: typeof AppShoppingPlannerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/statistics': {
      id: '/_app/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof AppStatisticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks': {
      id: '/_app/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/timeline': {
      id: '/_app/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof AppTimelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/today': {
      id: '/_app/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof AppTodayRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/transactions': {
      id: '/_app/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AppTransactionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAccountsRoute: typeof AppAccountsRoute
  AppAgendaRoute: typeof AppAgendaRoute
  AppBudgetsRoute: typeof AppBudgetsRoute
  AppCardsRoute: typeof AppCardsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppGoalsRoute: typeof AppGoalsRoute
  AppImportRoute: typeof AppImportRoute
  AppImportPrintsRoute: typeof AppImportPrintsRoute
  AppIncomeRoute: typeof AppIncomeRoute
  AppInvestmentsRoute: typeof AppInvestmentsRoute
  AppNotesRoute: typeof AppNotesRoute
  AppRechargesRoute: typeof AppRechargesRoute
  AppRecurringRoute: typeof AppRecurringRoute
  AppRoutinesRoute: typeof AppRoutinesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppShoppingPlannerRoute: typeof AppShoppingPlannerRoute
  AppStatisticsRoute: typeof AppStatisticsRoute
  AppTasksRoute: typeof AppTasksRoute
  AppTimelineRoute: typeof AppTimelineRoute
  AppTodayRoute: typeof AppTodayRoute
  AppTransactionsRoute: typeof AppTransactionsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountsRoute: AppAccountsRoute,
  AppAgendaRoute: AppAgendaRoute,
  AppBudgetsRoute: AppBudgetsRoute,
  AppCardsRoute: AppCardsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppGoalsRoute: AppGoalsRoute,
  AppImportRoute: AppImportRoute,
  AppImportPrintsRoute: AppImportPrintsRoute,
  AppIncomeRoute: AppIncomeRoute,
  AppInvestmentsRoute: AppInvestmentsRoute,
  AppNotesRoute: AppNotesRoute,
  AppRechargesRoute: AppRechargesRoute,
  AppRecurringRoute: AppRecurringRoute,
  AppRoutinesRoute: AppRoutinesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppShoppingPlannerRoute: AppShoppingPlannerRoute,
  AppStatisticsRoute: AppStatisticsRoute,
  AppTasksRoute: AppTasksRoute,
  AppTimelineRoute: AppTimelineRoute,
  AppTodayRoute: AppTodayRoute,
  AppTransactionsRoute: AppTransactionsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
